### ISSUE TITLE
Test with LCD price tag / EAN recognition

### ISSUE THREAD

**Issue by serpico** [TTalex/open-prices-contribution-tools#1]
I drew the crop rectangle around the EAN in a picture of an LCD price tag over at prices.openfoodfacts.org - hoping my lazy-ass would have just to type the price and be done with it :grinning: 

- Should I write the issue here or there ? May be you have no plan to support LCD price tag's picture for the foreseeable future, then I shouldn't write at all haha.

**Comment by TTalex** [comment]
Heyo @serpico,

When I made the integration with open prices, I did add support for EAN recognition ! But it's a bit hidden.

You can access it during the cleanup phase, by switching the mode to barcode (see image below).

![c2](https://github.com/user-attachments/assets/9ba6f5ab-4703-4fdd-b8ed-a641f47d5aa4)

The accuracy isn't great on low quality images, but it can still save some time.

If you want to see it in action, I made a demo video here: https://github.com/openfoodfacts/open-prices-frontend/pull/1025. The second example (around 2min40) uses price tags with EAN.


Since the integration, the code in this repo is no longer up-to-date. So I'll probably close it soon. 
If you have more feedback, I guess it would be better to put them all in the main repo https://github.com/openfoodfacts/open-prices-frontend, mentioning the name of the experiment in the title (Contribution Assistant) :)
